### ISSUE TITLE
Rendered out of order

### ISSUE THREAD

**Issue by ulic75** [qwikifiers/cypress-qwik#9]
I'm experiencing an issue where nodes are rendered out of order with Qwik.  This only occurs when using cypress, not during normal use.  It occurs when using Firefox, Electron and cli (which I'm guessing is headless electron).

The three child elements are rendered in the correct order in the DOM however, the console log shows that the first element is always rendered last, even when you add more.  I took a quick look at the cypress-ct-qwik code and it's pretty simple.  I'm not sure what could be going on here, but in my actual component I have order relevant state that becomes untestable because things are no longer in the right order.

```tsx
import { component$ } from '@builder.io/qwik';

const Child = component$((props: { order: string }) => {
  console.log(props.order);
  return <div id={props.order} />;
});

describe('Sample', () => {
  it('should exist', () => {
    cy.mount(
      <div class="test">
        <Child order="1">1</Child>
        <Child order="2">2</Child>
        <Child order="3">3</Child>
      </div>
    );
    cy.get('.test').should('exist');
  });
});
```

**Comment by shairez** [comment]
Thanks for the report @ulic75 

yeah this sounds weird indeed
Basically the difference is in the render function (`render` vs `renderToStream`)

I'll have time to debug it only after next week

In the meantime if you can help me pin point the issue that'll be awesome

We need to figure out if the problem is with SSR vs non SSR

So I would try 2 things - 

1. Try to load your app in "dev mode" and see if that matters or not

2. Put a debugger in the console log and try to locate the source of creation and what's different between running it in Qwik server vs in Cypress 

Will you have time to help me with this?

Thanks 🙏

**Comment by ulic75** [comment]
I'm not sure what you mean by "dev mode".  If you mean `pnpm dev` just running the Qwik app that way then no the problem does not exist when running the app that way or in preview or in build/serve.  I'm going to be out of the office most of today, but I'll try to do some more digging.

**Comment by shairez** [comment]
@ulic75 thanks

I mean running it without `--ssr` flag (I think `pnpm dev` still adds it)

**Comment by ulic75** [comment]
So the dev script runs `vite --mode ssr`.  So I manually just ran `pnpm vite` and indeed I do see it print 2, 3, 1 instead of 1, 2, 3.  So I guess this is a qwik issue.  Let me know if you have other thoughts.

**Comment by shairez** [comment]
Thanks @ulic75 !
Yeah looks like a Qwik issue
Can you pleases file an issue about it in the Qwik repo?
